### Login user
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
	"email": "stefan.jankovic@lavitsolutions.com",
	"password": "seedpas5word_CHANGE_IT"
}

### Buy paid tokens
PUT http://127.0.0.1:8000/api/users/5f83455c-b11d-4c1e-986a-60b9127d7585/tokensCount
Authorization: Bearer 4|bRpRuXvmIeiC5TRggTqTn9BWBF4wwfBQfc7fmEvF02e3b2fa

{
	"paidTokens": 9999
}


### Activate user
POST http://127.0.0.1:8000/api/activations
Content-Type: application/json

{
	"licenseKey": "5f83455c-b11d-4c1e-986a-60b9127d7585",
	"website": "http://www.example.com"
}


### Send a request to the GPT assistant to retrieve a response
POST http://127.0.0.1:8000/api/content
Content-Type: application/json

{
	"keywords": "wordpress website",
	"licenseKey": "5f83455c-b11d-4c1e-986a-60b9127d7585",
	"website": "http://www.example.com"
}